#!/usr/bin/env node
// Turns the Claude Code skills in .claude/skills into the MCP server's
// prompts, so they travel with the server to every client instead of only
// reaching people working in this checkout.
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

const SKILLS = ".claude/skills";

const prompts = readdirSync(SKILLS, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort()
  .map((dir) => {
    const text = readFileSync(join(SKILLS, dir, "SKILL.md"), "utf-8");
    const match = /^---\n([\s\S]*?)\n---\n+([\s\S]*)$/.exec(text);
    if (!match) throw new Error(`${dir}/SKILL.md: no front matter`);
    const field = (key) => {
      const line = match[1].split("\n").find((l) => l.startsWith(`${key}:`));
      return line?.slice(key.length + 1).trim().replace(/^"(.*)"$/, "$1");
    };
    const name = field("name");
    const description = field("description");
    if (!name || !description) throw new Error(`${dir}/SKILL.md: name and description are required`);
    // argument-hint: "[project] [ticket-title]" names $0, $1, … in order
    const args = [...(field("argument-hint") ?? "").matchAll(/\[([a-z-]+)\]/g)].map((m) => m[1]);
    return { name, description, arguments: args, body: match[2].trimEnd() };
  });

writeFileSync(
  "src/mcp/prompts.generated.ts",
  `// Auto-generated by scripts/generate-prompts.mjs from ${SKILLS} — do not edit.\n` +
    `export const PROMPTS: { name: string; description: string; arguments: string[]; body: string }[] = ${JSON.stringify(prompts, null, 2)};\n`
);
