#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";

const pkg = JSON.parse(readFileSync("package.json", "utf-8"));
const version = process.env.APP_VERSION || pkg.version;

writeFileSync(
  "src/version.generated.ts",
  `// Auto-generated by scripts/inject-version.mjs — do not edit.\nexport const VERSION = ${JSON.stringify(version)};\n`
);
